name: Build kobo-clara-2e
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Install QEMU armv7 binfmt
        run: |
          sudo apt-get update -q
          sudo apt-get install -y qemu-user-static
          echo ':qemu-arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:F' \
            | sudo tee /proc/sys/fs/binfmt_misc/register
          cat /proc/sys/fs/binfmt_misc/qemu-arm

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            extra-platforms = armv7l-linux aarch64-linux
            system-features = benchmark big-parallel nixos-test uid-range gccarch-armv7-a

      - name: Restart Nix daemon
        run: |
          sudo tee -a /etc/nix/nix.conf <<'EOF'
          extra-platforms = armv7l-linux aarch64-linux
          system-features = benchmark big-parallel nixos-test uid-range gccarch-armv7-a
          EOF
          sudo systemctl restart nix-daemon
          sleep 5
          nix store info
          nix config show | grep -E 'extra-platforms|system-features'

      - uses: cachix/cachix-action@v15
        with:
          name: dotfilekoboc17cb2c57affa23f8de7
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build kobo-clara-2e
        run: nix build .#hydraJobs.kobo-clara-2e
